---
name: pysb
channels:
  - conda-forge
dependencies:
  - alubbock::bionetgen
  - alubbock::nfsim==1.12.1
  - alubbock::atomizer
  - alubbock::kappa
  - numpy
  - scipy
  - sympy
  - cython
  - matplotlib
  - networkx
  - h5py
  - pexpect
  - pandas
  - pydot<4
  - coverage
  - pip
  # setuptools required by Cython
  # https://github.com/cython/cython/issues/5976
  - setuptools
  - pip:
      - libroadrunner
      - python-libsbml
      - pynose
