---
name: pysb
channels:
  - conda-forge
dependencies:
  - alubbock::nfsim==1.12.1
  - alubbock::atomizer
  - alubbock::kappa
  - numpy
  - scipy
  - sympy<1.12
  - cython
  - matplotlib
  - networkx
  - h5py
  - pexpect
  - pandas
  - pydot
  - coverage
  - coveralls
  - mock
  - pip
  - pip:
      - libroadrunner
      - python-libsbml
      - pynose
      - bionetgen
