#!/usr/bin/env python
"""
A class for getting the BNGL NET file for a given PySB model. Serves as a
command-line wrapper around ``pysb.bng.generate_network()``, which generates
the BNGL for the model and then invokes BNG to generate the NET file.
"""

from pysb.bng import generate_network
from pysb.export import Export

class ExportBngNet(Export):
    def export(self):
        """Generate the BNGL NET file for ``self.model``.
        A wrapper around ``pysb.bng.generate_network()``.

        Returns
        -------
        string
            The NET file output for the model, generated by BNG.
        """
        return generate_network(self.model, append_stdout=True)

